### ISSUE TITLE
Improve callback API

### ISSUE THREAD

**Issue by rkolesnev-vineti** [ffloyd/flows#6]
The work to be done:

* split SCP context into explicit `:data` and `:meta` parts.
* vanilla SCP must left `meta` in context and results empty
  * with exception for `:last_step` meta-field for (at least) failure results of SCP
* signatures for callbacks must be:
    * `before_all(klass, data, meta) -> void`
    * `after_all(klass, result, data, meta) -> new_result`
    * `before_each(klass, step_name, data, meta) -> void`
    * `after_each(klass, step_name, result, data, meta) -> new_result`
* `data` and `meta` are mutable hashes
* `after_each` is executed before result data merged to the pipeline context

**Comment by ffloyd** [comment]
After some thoughts, I've decided to not make `after_each` be able to substitute the step's result:

* it has bad compatibility with mutation steps
* it's a bad idea to change result returned by a business code - it can lead to implicit unexpected behaviour

**Comment by ffloyd** [comment]
So, new spec for `after_each`:

* `after_each(klass, step_name, result, data, meta) -> void`
* `after_each` is executed **after** result data merged to the pipeline context
